# Generated by Django 2.2.5 on 2022-01-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220120_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
