# Generated by Django 4.0.2 on 2022-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
