# Generated by Django 2.2.5 on 2022-01-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220120_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
