# Generated by Django 4.0.2 on 2022-03-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tile',
            new_name='title',
        ),
    ]
